version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: surfer
      POSTGRES_USER: surfer
      POSTGRES_PASSWORD: surfer
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL:-http://localhost:8080/api/v1/auth/google/callback}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-change-this}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=surfer
      - DB_PASSWORD=surfer
      - DB_NAME=surfer
      - DB_SSLMODE=disable
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend

volumes:
  postgres-data:
