services:
  postgres:
    image: postgres:15-alpine
    network_mode: host
    environment:
      POSTGRES_DB: surfer
      POSTGRES_USER: surfer
      POSTGRES_PASSWORD: surfer
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U surfer -d surfer"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    network_mode: host
    environment:
      - PORT=8080
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL:-http://localhost:8080/api/v1/auth/google/callback}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-change-this}
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_USER=surfer
      - DB_PASSWORD=surfer
      - DB_NAME=surfer
      - DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    network_mode: host
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend

volumes:
  postgres-data:
