apiVersion: v1
kind: Service
metadata:
  name: {{ include "surfer.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "surfer.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "surfer.frontend.selectorLabels" . | nindent 4 }}
