---
name: Setup GitHub Pages for Helm Repository

on:
  push:
    branches: [main]
    paths:
      - 'helm/surfer/**'
      - '.github/workflows/gh-pages-setup.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setup-gh-pages:
    name: Setup Helm Repository Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Create Helm repository structure
        run: |
          mkdir -p helm-repo/charts

      - name: Package latest Helm chart
        run: |
          helm package helm/surfer --destination helm-repo/charts

      - name: Generate Helm repository index
        run: |
          cd helm-repo
          helm repo index charts --url https://mysticrenji.github.io/surfer/charts

      - name: Copy repository index HTML
        run: |
          cp helm-repo-index.html helm-repo/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm-repo
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update Helm repository'
